- web/index.html
Update the wording to say: Online, Worldwide
> Clarify that the conference is Online

- web/index.html
> Add cfp url

- web/about.html
- web/generate_site/templates/footer.html
- web/generate_site/templates/index-base.html
- web/index.html
Added our email address to the "Contact" section.
Added an envelope icon to the footer next to social icons.
How it looks like with this change:
> Add email address to contact and footer sections.

- css/style.css
- generate_site/templates/about-base.html
> Few changes to improve a11y

- css/style.css
- generate_site/templates/sponsors-base.html
quick fix to make the sponsorship table a bit more mobile-friendly 
https://github.com/pyladies/global-conference/assets/838923/47899dae-3b1a-4094-bcf3-c14b9271b655
> quick fix for sponsorship page table

- generate_site/templates/footer.html
> Adjust Awesomic logo

- generate_site/templates/header.html
- generate_site/templates/speakers-base.html
> Add Keynotes and Speaker to the menu

- generate_site/templates/footer.html
Add rel="me" to the mastodon url
Closes #84
> Verify Mastodon Account

- generate_site/generate.py
- generate_site/templates/about-base.html
- generate_site/templates/coc-enforcement-base.html
- generate_site/templates/coc-reporting-base.html
- web/README.md
This PR adds:
- CoC enforcement procedures
- CoC reporting procedures
> 📝 Add Code of Conduct procedures

- generate_site/templates/about-base.html
- generate_site/templates/header.html
> Add PSF section to about

- generate_site/templates/index-base.html
> Add missing sponsors

- content/news/save_the_date.md
- themes/pyladies/layouts/news/single.html
- themes/pyladies/layouts/partials/components/blog-card.html
- themes/pyladies/layouts/partials/news-footer.html
- Add blog post time
- Add footer
- Remove text from the news because it's now part of the footer
> Minor update to the News template

- content/news/call-for-sponsors.md
Added text for call sponsors (based on last year's) 
Let me know if I should have done anything differently.
> added call for sponsors

- content/news/speaker-support.md
- Add Lorena and Sayantika as mentors
- Add all the language options of the mentors
I also update the date to bump this post to the top.
> Update speaker-support.md - adding mentors and language options

- content/news/speaker-support.md
> Adding Maria Jose as mentor

- content/sponsors/_index.md
- themes/pyladies/layouts/shortcodes/attendeejobtable.html
Added attendee job types to sponsorship page via shortcode attendeejobtable.
Also fixed a couple of types while I was at it.
> Attendee jobs

- content/_index.md
- content/news/ cfp-outreach-kit-french.md
- content/news/ cfp-outreach-kit-japanese.md
- content/news/ cfp-outreach-kit-portuguese.md
- content/news/ cfp-outreach-kit-spanish.md
- content/news/ cfp-outreach-kit-tchinese.md
- content/news/_index.md
- content/news/cfp-outreach-kit.md
- themes/pyladies/layouts/partials/footer.html
- themes/pyladies/layouts/partials/news-footer.html
This solves issue https://github.com/pyladies/global-conference/issues/143
> added youtube link to sites where social media was already displaying

- content/about/sprints.md
Hello, and thank you for organizing the conference and the sprint! I am one of the maintainers of the [Skrub](https://skrub-data.org/) library ([github repository](https://github.com/skrub-data/skrub/) ) and we would like to participate in the sprint
> Add skrub to list of sprint projects

- content/about/sprints.md
Hi! I would like to propose a project for the sprints: The translation of the Python Documentation into Spanish.
There are a lot of [issues](https://github.com/python/python-docs-es/issues) waiting for anyone who wants to collaborate ❤️ 
Thank you!
cc @mjmolina
> python doc ES sprint proposal

- src/pages/docs/[single].astro
> Fix relative docs sidebar

- src/config/social.json
- src/content/authors/cheuk.md
- src/content/authors/denny-perez.md
- src/content/authors/mariatta.md
- src/content/authors/naomi-ceder.md
- src/content/posts/2025-pyladiescon-is-back.mdx
- src/layouts/PostSingle.astro
- src/pages/rss.xml.js
- Create Rss feed at /rss.xml
- Link to the RSS Feed at the footer
- Add the social media info and feed as part of the blog post footer
- Update meta author info
Closes https://github.com/pyladies/global-conference/issues/209
> Create RSS Feed

- src/layouts/PostSingle.astro
Should be rss.xml instead of feed.xml
> Fix the link to rss in the blog post footer
